### ISSUE TITLE
Error DocumentReader.js

### ISSUE THREAD

**Issue by bambang-ap** [robsmith100/sav#1]
I have an error like this
![Code_5PAGiKCAxa](https://user-images.githubusercontent.com/18139422/87520396-19a35d80-c6ad-11ea-84d9-ad53b06cccc0.png)

and i I remove "doc" variable in DocumentReader.js, i got another error

![Code_b33Wj1CRMc](https://user-images.githubusercontent.com/18139422/87520533-46f00b80-c6ad-11ea-8dc5-fdea8e11cd46.png)

**Comment by robsmith100** [comment]
Sorry I'm so late answering. If you post a simple snippet of code that demonstrates your usage, I can help diagnose.
