### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by gtamas** [robsmith100/sav#2]
Are still actively working on this or it's dead?

We wanna use this package to replace our weird R scripts, but if it's abandoned then we should look for other solutions.
Too bad, as far as I can see, this is the best spss package on NPM.

**Comment by robsmith100** [comment]
Hey sorry, I am totally new to open source contribution and didn't even see your question. It's not dead and I'll fix things as needed. I plan to use this more heavily in the future. I'll look into getting my notifications working.
